### ISSUE TITLE
Allow select and copy-paste

### ISSUE THREAD

**Issue by tibortiz** [ovh/tygenie#6]
With the current version (1.6.4), I'm not able to select and copy content from tygenie output like fields from OpsGenie alert description.

**Comment by pslestang** [comment]
This is because the terminal is in application mode which disables clicking and dragging to select text. :

https://textual.textualize.io/FAQ/#how-can-i-select-and-copy-text-in-a-textual-app

Depending the terminal you are using to select/paste use the following key:

- iTerm Hold the OPTION key.
- Gnome Terminal Hold the SHIFT key.
- Windows Terminal Hold the SHIFT key.
